# Generated by Django 4.2.17 on 2025-01-14 04:28

from django.db import migrations, models
import django.db.models.deletion
import medical.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bloodtype', models.CharField(max_length=20)),
                ('allergies', models.CharField(max_length=100)),
                ('medications', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('civil_status', models.CharField(max_length=20)),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('parent_guardian', models.CharField(max_length=100)),
                ('parent_guardian_contact_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lrn', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(max_length=100)),
                ('year_level', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityForm',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medical.patient')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('competetions', models.CharField(max_length=100)),
                ('date_of_event', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date_of_examination', models.CharField(max_length=100)),
                ('liscence_number', models.CharField(max_length=50)),
                ('validity_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medical.patient')),
                ('college', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bp', models.CharField(max_length=20)),
                ('p', models.CharField(max_length=20)),
                ('t', models.CharField(max_length=20)),
                ('rr', models.CharField(max_length=20)),
                ('sports_played', models.CharField(max_length=255)),
                ('physically_able', models.BooleanField(default=False)),
                ('physically_not_able', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalClearance',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transac_type', models.CharField(max_length=100)),
                ('transac_date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cardiovascular_disease', models.BooleanField(default=False)),
                ('chronic_lung_disease', models.BooleanField(default=False)),
                ('chronic_renal_disease', models.BooleanField(default=False)),
                ('chronic_liver_disease', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('autoimmune_disease', models.BooleanField(default=False)),
                ('pwd', models.BooleanField(default=False)),
                ('disability', models.CharField(blank=True, max_length=255)),
                ('clearance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=50)),
                ('treatment', models.CharField(max_length=50)),
                ('date_prescribed', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_physical_examination', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.student')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=100)),
                ('approve', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField()),
                ('date_approved', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.physicalexamination'),
        ),
        migrations.AddField(
            model_name='patient',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.student'),
        ),
        migrations.CreateModel(
            name='ObgyneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menarche', models.CharField(blank=True, max_length=100, null=True)),
                ('lmp', models.CharField(blank=True, max_length=100, null=True)),
                ('pap_smear', models.CharField(blank=True, max_length=100, null=True)),
                ('gravida', models.CharField(blank=True, max_length=10, null=True)),
                ('para', models.CharField(blank=True, max_length=10, null=True)),
                ('menopause', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_history', models.CharField(blank=True, max_length=255, null=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.physicalexamination')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccinated_1st', models.BooleanField(blank=True, default=False, null=True)),
                ('vaccinated_2nd', models.BooleanField(blank=True, default=False, null=True)),
                ('vaccinated_booster', models.BooleanField(blank=True, default=False, null=True)),
                ('x_ray_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('cbc_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_test_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('stool_examination_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('chest_xray', models.FileField(upload_to=medical.models.MedicalRequirement.chest_xray_path)),
                ('cbc', models.FileField(upload_to=medical.models.MedicalRequirement.cbc_path)),
                ('drug_test', models.FileField(upload_to=medical.models.MedicalRequirement.drug_test_path)),
                ('stool_examination', models.FileField(upload_to=medical.models.MedicalRequirement.stool_examination_path)),
                ('pwd_card', models.FileField(blank=True, null=True, upload_to=medical.models.MedicalRequirement.pwd_id_card_path)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuberculosis', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('hernia', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('peptic_ulcer', models.BooleanField(default=False)),
                ('kidney_disease', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('insomnia', models.BooleanField(default=False)),
                ('malaria', models.BooleanField(default=False)),
                ('venereal_disease', models.BooleanField(default=False)),
                ('allergic_reaction', models.BooleanField(default=False)),
                ('nervous_breakdown', models.BooleanField(default=False)),
                ('jaundice', models.BooleanField(default=False)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('no_history', models.BooleanField(default=False)),
                ('hospital_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('medications', models.CharField(blank=True, max_length=255, null=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.physicalexamination')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=True)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('bleeding_disorder', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('mental_disorder', models.BooleanField(default=False)),
                ('no_history', models.BooleanField(default=False)),
                ('other_medical_history', models.CharField(blank=True, max_length=100, null=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.physicalexamination')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyHealthAssistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('date_assisted', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DentalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('date_requested', models.DateTimeField()),
                ('date_appointed', models.DateField(null=True)),
                ('appointed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
    ]
