# Generated by Django 4.2.17 on 2025-01-24 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_mentalhealthrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalhealthrecord',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='mentalhealthrecord',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='examination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.physicalexamination'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.student'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.student'),
        ),
    ]
