# Generated by Django 5.1.4 on 2025-01-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_mentalhealthrecord_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='clearance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.medicalclearance'),
        ),
    ]
