# Generated by Django 5.1.4 on 2025-01-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_riskassessment_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='medical_clearance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskassessment', to='medical.medicalclearance'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='clearance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
    ]
