# Generated by Django 5.1.4 on 2025-02-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_riskassessment_medical_clearance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='medical_clearance',
            new_name='medical_clearance_id',
        ),
    ]
